### ISSUE TITLE
How to install keystone-forgotten-password ?

### ISSUE THREAD

**Issue by sdadoun** [Thinkmill/keystone-forgotten-password#6]
Hello,
    I have difficulties to install keystone-forgotten-password.

I installed keystoneJS version 4.0.0-beta.5 with
```
$ npm install -g generator-keystone
$ yo keystone
```
and it is working well.

Then I install keystone-forgotten-password with :
```
$ cd keystone
$ npm install -g keystone-forgotten-password
```
which displayed :
```
npm WARN keystone-forgotten-password@1.4.0 requires a peer of express@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN keystone-forgotten-password@1.4.0 requires a peer of keystone@4.0.0-beta.5 but none is installed. You must install peer dependencies yourself.

+ keystone-forgotten-password@1.4.0
updated 2 packages in 3.667s
```
then in routes/index.js when I add :
`const forgottenPasswordPlugin = require('keystone-forgotten-password');
`
and I run keystone :
`$ node keystone
`
It displays this error :
`Error: Cannot find module 'keystone-forgotten-password'
`

Do you have an idea what I did wrong ? Should I use github repository instead of npm ?

Thanks
Simon

**Comment by export-mike** [comment]
You do not install globally,

```npm install keystone-forgotten-password --save```

**Comment by sdadoun** [comment]
Thanks it worked.

**Comment by export-mike** [comment]
@JedWatson @Noviny @thejameskyle good to close I no longer have perms .
